### ISSUE TITLE
Do not depend on the ANDROID_HOME environment variable.

### ISSUE THREAD

**Issue by bu2zhouzhu** [pedrovgs/AndroidWiFiADB#12]
I had tried to declare system variable ANDROID_HOME with values 'D:\Users\Administrator\AppData\Local\Android', 'D:\Users\Administrator\AppData\Local\Android\sdk', 'D:\Users\Administrator\AppData\Local\Android\sdk\platform-tools', 'D:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe', but none of them work. The plugin kept saying that 'adb commond not found. Review your Android SDK installation'. I also had declared user variable 'ANDROID_HOME', it's not work too. My PC is WIN7.

**Comment by tonyjs** [comment]
I'm too. Using mac osx(yosemite). /Users/userid/android-sdk-macosx/platform-tools.
same error occurred. 'adb commond not found. Review your Android SDK installation'

**Comment by pedrovgs** [comment]
@tonyjs @bu2zhouzhu don't worry about the ANDROID_HOME var. I'm going to merge a PR from @JcMinarro to remove this requirement. The next version I'll publish, 1.2, will remove the usage of this variable and the plugin will work even if you don't declare it. Sorry for the inconveniences.

**Comment by pedrovgs** [comment]
The PR is here -> #11. Maybe you want to take a look.

**Comment by ruancaipu** [comment]
error 
  Android WiFi ADB: 'adb' command not found. Review your Android SDK installation.

**Comment by pedrovgs** [comment]
The new version I've released fixes this issue. Thanks for your help!
