### ISSUE TITLE
Version 1.1 not working on windows 10 with ANDROID_HOME variable path.

### ISSUE THREAD

**Issue by pinakinkansara** [pedrovgs/AndroidWiFiADB#13]
I have installed version 1.1 just now  but it also fails to connect to device over wifi.

error : adb command not found , Review your android SDK installation.

my environment variable setting
ANDROID_HOME = D:\SOFTWARE\adt_bundle\sdk\platform-tools

**Comment by pedrovgs** [comment]
@pinakinkansara your android home should point at D:\SOFTWARE\adt_bundle\sdk not at platform-tools

**Comment by pinakinkansara** [comment]
@Pedro I did the change as you mentioned in my ANDROID_HOME , and it still
gives the same error message.

On Thu, Oct 22, 2015 at 7:10 PM Pedro Vicente Gómez Sánchez <
notifications@github.com> wrote:

> @pinakinkansara https://github.com/pinakinkansara your android home
> should point at D:\SOFTWARE\adt_bundle\sdk not at platform-tools
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pedrovgs/AndroidWiFiADB/issues/13#issuecomment-150226427
> .
> 
> ## 

_Pinakin Kansara_ / Sr Mobile Application Developer
pinakin.k.kansara@gmail.com / +91 9099721222/

 Skype :- pinakin.kansara

_Vedanta Soft_

www.vedantasoft.com http://signature-maker.net/www.vedantasoft.com

**Comment by pedrovgs** [comment]
Did you restart your IDE? Next week I'm going to publish a version where the ANDROID_HOME is not needed. If you don't get the plugin working today wait for the next release. Sorry for the inconveniences.

**Comment by ranjithstar256** [comment]
Hi me too facing the same issue.. Will wait for the update.. Thanks..

Ranjith,
(ranjithstar256@gmail.com)

**Comment by uditunpluged** [comment]
Please add a fix for OS X.... v1.1 same error on mac

**Comment by pedrovgs** [comment]
I've released a new version which fixes this issue. Thanks for your help :)

**Comment by pinakinkansara** [comment]
Thanks @Pedrovgs , Version 1.2 is working like charm

**Comment by pedrovgs** [comment]
You are welcome @pinakinkansara Thanks for your help reporting problems with the plugin!!

**Comment by ranjithstar256** [comment]
Hi @pedrovgs, 

can you help me why i am getting this error? when click on the AndroidWifiADB icon in the top?

" StringIndexOutOfBoundsException: String index out of range: -5 "
![untitled](https://cloud.githubusercontent.com/assets/7418487/10754626/e50c25d0-7cbe-11e5-901b-967ab9df82ca.jpg)

**Comment by pedrovgs** [comment]
Which version are you using?

**Comment by razi3742** [comment]
i am facing same issue  on android studio 1.5 Android WiFi ADB threw an uncaught StringIndexOutOfBoundsException
![untitled](https://cloud.githubusercontent.com/assets/6662328/11365771/98534058-92ca-11e5-8751-6069a0463095.png)
![untitsadled](https://cloud.githubusercontent.com/assets/6662328/11365882/767ccf66-92cb-11e5-8475-6cdbc87b64cc.png)

**Comment by pedrovgs** [comment]
@razi3742 can you try with the latests version I've published? It's already available in the IntelliJ Plugin's Store.
