### ISSUE TITLE
Exception thrown when running USB to WIFI

### ISSUE THREAD

**Issue by danlegion** [pedrovgs/AndroidWiFiADB#14]
I have installed the plugin from the repository inside the Android Studio.
Version installed is 1.0.1
I am running AS 1.4
ANDROID_HOME is created and added to my path
I have restarted AS and adb several times and I get the same exception when trying to do USB to WIFI
![screen shot 2015-10-23 at 10 26 46 am](https://cloud.githubusercontent.com/assets/2336246/10699020/25895f98-7971-11e5-8756-ed3a76e1edf2.png)

**Comment by ruancaipu** [comment]
The first connection must be connected with the USB？？

**Comment by danlegion** [comment]
Yes. My device was connected

**Comment by ruancaipu** [comment]
Thanks!If you don't have to connect with USB, it's perfect. Look forward to

**Comment by danlegion** [comment]
Hey @yyloveruancaipu I meant that my device was connected to USB when I got the exception.

**Comment by pedrovgs** [comment]
Hey @danlegion I've released the version 1.2. Can you review if your still have this problem with the plugin?

You can download it from the official IntelliJ Plugin Store: https://plugins.jetbrains.com/plugin/7983

**Comment by danlegion** [comment]
Hey @pedrovgs it works phenomenally well! Thanks for the plugin.

**Comment by pedrovgs** [comment]
You are welcome @danlegion I'll close this issue :)
