### ISSUE TITLE
Sorry i could not find it in the reposotiroes from Android studio

### ISSUE THREAD

**Issue by Shajeel-Afzal** [pedrovgs/AndroidWiFiADB#16]
Hi, I searched for Android WiFi ADB but i could not find it from the repositories, can you please check?

**Comment by pedrovgs** [comment]
Open you IDE and then go to Preferences/Settings->Plugins->Browse Repositories. Then you can search Android WiFi ADB and install the plugin. If you don't find the plugin you can download it from this link https://plugins.jetbrains.com/plugin/7983 and install it manually. Is this the answer to your question?

**Comment by Shajeel-Afzal** [comment]
I don't see it in my Android Studio, you can see in the screenshot, also your latest version that you released today is not approved so far on Jetbrains. 

<img width="818" alt="screen shot 2015-10-25 at 10 41 20 pm" src="https://cloud.githubusercontent.com/assets/3718283/10716914/d7d2adfe-7b69-11e5-8032-fc8396731f7b.png">
<img width="800" alt="screen shot 2015-10-25 at 10 42 15 pm" src="https://cloud.githubusercontent.com/assets/3718283/10716915/da11507a-7b69-11e5-9fd8-2f473c9b8f1c.png">

Thanks for making this.

**Comment by pedrovgs** [comment]
@Shajeel-Afzal the version I've released today is wait for approve. I hope tomorrow will be ready to download. I don't know this plugin does not appear in Android Studio :( I'm using IntelliJ right now and the plugin is available.

![captura de pantalla 2015-10-25 a las 18 47 38](https://cloud.githubusercontent.com/assets/4030704/10716958/44fb14be-7b49-11e5-9bc9-6c5621c6bd6f.png)

I'm going to send an email to the IntelliJ guys to check what's going on. Thanks!

**Comment by vanniktech** [comment]
I also could not find it yesterday, however today I found it and could install it.

**Comment by pedrovgs** [comment]
@Shajeel-Afzal can you try again? I've sent an email to the IntelliJ Store support guys but I don't have answer jet.

**Comment by pedrovgs** [comment]
I've checked this issue by my self again and as @vanniktech says, the plugin is already available in the Android Studio store. I'm closing this issue. Thanks for your help!
