### ISSUE TITLE
adb command not found..

### ISSUE THREAD

**Issue by Rowandjj** [pedrovgs/AndroidWiFiADB#17]
<img width="516" alt="2015-10-26 10 22 03" src="https://cloud.githubusercontent.com/assets/5766252/10719851/75af804a-7bcb-11e5-9cb3-371b68ec330e.png">
but i have already setting ANDROID_HOME environmental variable,adb command can found in terminal.

**Comment by danielsunyu** [comment]
I have the same issue...

**Comment by pedrovgs** [comment]
@dannysuen @Rowandjj I've released a new version to avoid the usage of this ANDROID_HOME var. Can you update your plugin installation. This is already fixed :)
