### ISSUE TITLE
Device connected successful,but device disconnect after disconnected USB

### ISSUE THREAD

**Issue by treycc** [pedrovgs/AndroidWiFiADB#19]
![abc](https://cloud.githubusercontent.com/assets/15090153/10723958/2644dc32-7bfb-11e5-865a-c6373099d703.PNG)
![cde](https://cloud.githubusercontent.com/assets/15090153/10724035/03b15b36-7bfc-11e5-8d92-3506652ee679.PNG)

Device connection is successful, the connected devices list there are two devices, but after disconnected USB, the two devices are gone.
This phone and my computer can transfer data via the same WIFI.
Maybe WIFI ADB is not compatible with my phone?

phone:moto x style
pc:win8.1

**Comment by pedrovgs** [comment]
@treycc I have bad news for you, the problems related with the device connection once the device has been connected over WiFi is something we can't fix from our plugin. Review if you are using the last adb version of if there is any problem with your device or your WiFi configuration. From my side it's impossible to fix this issue :(

**Comment by treycc** [comment]
@pedrovgs thanks

**Comment by pedrovgs** [comment]
I'm so sorry. I'd like to improve this, but I can't improve the Android Debug Bridge from my side.

**Comment by treycc** [comment]
@pedrovgs i try to check whether there is problem with Android Debug Bridge,or try an other phone
