### ISSUE TITLE
can't useable

### ISSUE THREAD

**Issue by emile2013** [pedrovgs/AndroidWiFiADB#20]
In intellij Event Log window shows  error like that: 
StringIndexOutOfBoundsException: String index out of range: -4

**Comment by pedrovgs** [comment]
@emile2013 which plugin version are you using?  Can you try to execute this commands and paste the output here?

```
adb tcpip 5555
adb connect 192.168.2.131
```

Replace 192.168.2.131 with the IP assigned to your device.

Thanks!

**Comment by emile2013** [comment]
hi, @pedrovgs :
    I'm using the version of 1.2 . and i had executed the commands that you offer,and the outputs like  that:
     unable to connect to 172.18.3.52:5555

```
ps: 172.18.3.52  is  my ip  address 
```

**Comment by pedrovgs** [comment]
@emile2013 did you connect your device to the computer using a USB cable before to execute the command?
