### ISSUE TITLE
Unable to connect device 'GT_I9300'. Review your connection

### ISSUE THREAD

**Issue by vanniktech** [pedrovgs/AndroidWiFiADB#21]
I'm using the 1.2 version of this plugin together with AS 1.5 Preview 2.

The S3 is in my WiFi and I can also ping to it from my computer and vice versa.

Do you know what could be the issue?

**Comment by Android-s14** [comment]
I have the same problem. Tried 4.4.2 and 6.0 devices. Are there any special preconditions needed?

**Comment by diogochbittencourt** [comment]
Same problem here. Nexus 4, Android 5.1.1, plugin 1.2.

**Comment by pedrovgs** [comment]
@diogochbittencourt @Android-s14 @vanniktech can you try to execute this commands and paste the output here?

```
adb tcpip 5555
adb connect 192.168.2.131
```

Replace 192.168.2.131 with the IP assigned to your device.

Thanks!

**Comment by vanniktech** [comment]
Hmm I'm sorry but I can't reproduce it anymore. Now the plugin does work for me. In case it won't during this day, I'll post the output here.

**Comment by Android-s14** [comment]
```
> adb tcpip 5555
restarting in TCP mode port: 5555
> adb connect 172.20.40.77
unable to connect to 172.20.40.77:5555
```

**Comment by hegazy** [comment]
@pedrovgs I have GTI9500 and the commands you provided is working.
@Android-s14 Did you connect it using USB first before executing these commands?

**Comment by Android-s14** [comment]
@hegazy yes

**Comment by pedrovgs** [comment]
@Android-s14 are you connected to any special WiFi network? Can you try using another WiFi connection?

**Comment by Android-s14** [comment]
That's a corporate network, and I understand there's probably not much the plugin can do, since it's more of an adb problem. I was just hoping there's some workaround for this problem. The plugin works fine for me in my home network.

**Comment by pedrovgs** [comment]
These problems are not related with the plugin. If the environment where adb is executed is not supported because the Wifi ports configuration is not working as should or because you don't connect the device at your computer before to press the button the plugin does not work. I'm going to cose this issues because all the people commenting here have already solve their problems. Thanks for your help!

**Comment by vanniktech** [comment]
Thanks for your awesome plugin @pedrovgs
