### ISSUE TITLE
Device connected successful,but device disconnect after disconnected USB Cable

### ISSUE THREAD

**Issue by VivekKumarApps** [pedrovgs/AndroidWiFiADB#22]
Hello,  

I am able to connect the device successfully but it disconnect when the USB cable is disconnect.
But this is working fine for below lollipop devices(below 5.0), this is not working on 5.0 or above devices.

I am waiting for your response.

Thanks,
Vivek Kumar

**Comment by SandyDheringe** [comment]
Yes same thing observed by me

**Comment by pedrovgs** [comment]
I'm sorry guys, but I've already closed the same issue few minutes ago. The problem is not related with my plugin. Read this issue comments to get more information #19 .
