### ISSUE TITLE
IOException is thrown when you click on the toolbar button to establish connection. 

### ISSUE THREAD

**Issue by YZakher** [pedrovgs/AndroidWiFiADB#23]
Broken pipe java.io.IOException: Broken pipe at sun.nio.ch.FileDispatcherImpl.write0(Native Method) at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) at sun.nio.ch.IOUtil.write(IOUtil.java:65) at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470) at com.android.ddmlib.JdwpPacket.writeAndConsume(JdwpPacket.java:213) at com.android.ddmlib.Client.sendAndConsume(Client.java:684) at com.android.ddmlib.HandleHeap.sendREAQ(HandleHeap.java:349) at com.android.ddmlib.Client.requestAllocationStatus(Client.java:523) at com.android.ddmlib.DeviceMonitor.createClient(DeviceMonitor.java:569) at com.android.ddmlib.DeviceMonitor.openClient(DeviceMonitor.java:544) at com.android.ddmlib.DeviceMonitor.processIncomingJdwpData(DeviceMonitor.java:506) at com.android.ddmlib.DeviceMonitor.deviceClientMonitorLoop(DeviceMonitor.java:402) at com.android.ddmlib.DeviceMonitor.access$100(DeviceMonitor.java:64) at com.android.ddmlib.DeviceMonitor$1.run(DeviceMonitor.java:325)

**Comment by pedrovgs** [comment]
Are you sure that you are using my plugin? That's trace does not seem related to my plugin because I don't use DDMLIB in my project :(

**Comment by YZakher** [comment]
I am using version 1.2, here is the link
https://plugins.jetbrains.com/plugin/7983?pr=&showAllUpdates=true

**Comment by pedrovgs** [comment]
I'm sorry but I can't help you. Reviewing the trace the error is related to the IntelliJ AndroidSdkUtils class I'm using. I guess if you update your IntelliJ/Android Studio version this bug will be fixed. Sorry but I can't change the code of my plugin to fix this :(
