### ISSUE TITLE
Icon not showing in the toolbar

### ISSUE THREAD

**Issue by root1** [pedrovgs/AndroidWiFiADB#25]
i installed the plugin and restarted android studio but the icon to switch to wifi debug is still not showing

**Comment by SaitejaP** [comment]
I am using studio 1.4.1. Same issue here

**Comment by pedrovgs** [comment]
@root1 @SaitejaP can you upload an screenshot of the plugin you've installed? If you've installed the plugin and restarted the IDE you should see the icon. Review also that your toolbar is visible in the view options. Thanks!

**Comment by SaitejaP** [comment]
<img width="370" alt="screen shot 2015-10-27 at 4 15 25 pm" src="https://cloud.githubusercontent.com/assets/6340565/10755830/2d8fb022-7cc6-11e5-810f-dd1b501d64f0.png">

Here is the screenshot. I am trying to use the tool from `tool -> android -> adb wifi -> adb usb to wifi`. Still I could not use adb over wifi but when I disconnect usb, studio prompts `device '192.168.1.102:5555' not found` . FYI, My device is rooted and i am using studio on mac.

**Comment by pedrovgs** [comment]
@SaitejaP you are not using my plugin. You've installed another one!

![facepal](https://media.giphy.com/media/ADr35Z4TvATIc/giphy.gif)

**Comment by SaitejaP** [comment]
Oops! I installed the correct plugin from disk downloaded from [here](https://plugins.jetbrains.com/plugin/7983). This time, the icon is visible and could connect over wifi. But when I disconnect usb (after confirming the connected devices using `adb devices` command), it also disconnects over wifi.

**Comment by pedrovgs** [comment]
Your problem is not related to my plugin. Your problem is related to your adb installation. I can't change my plugin to fix your problem. Update your adb installation and everything should be fine.

**Comment by malmstein** [comment]
![giphy](https://cloud.githubusercontent.com/assets/531613/10757547/adf85a7a-7ca3-11e5-8f13-1ef779e486fd.gif)

**Comment by saulmm** [comment]
![choice](https://cloud.githubusercontent.com/assets/3531999/10765452/21c5cd3c-7cd3-11e5-932f-f056901beb9a.gif)

**Comment by cesards** [comment]
![wroooong](https://cloud.githubusercontent.com/assets/1536079/10770828/a4e0d382-7ced-11e5-80bd-e226f7fe89b8.gif)
