### ISSUE TITLE
Icon not shown when toolbar its hidden

### ISSUE THREAD

**Issue by saulmm** [pedrovgs/AndroidWiFiADB#32]
It would be nice to show the adb wifi icon even if the toolbar is hidden, as Fabric does 

<img width="1262" alt="screen shot 2015-11-12 at 21 42 32" src="https://cloud.githubusercontent.com/assets/3531999/11130656/782c63c4-8986-11e5-99ed-0d54a37fe4f9.png">

**Comment by pedrovgs** [comment]
Wow @saulmm it could be great if you collaborate with this project implementing this feature!

**Comment by pedrovgs** [comment]
Look @saulmm a new version is coming!
