### ISSUE TITLE
It is not working for MOTO E2 but for other device it is working fine

### ISSUE THREAD

**Issue by ShreyashPromact** [pedrovgs/AndroidWiFiADB#38]
Hello,

I have some different devices with me to test. Many of them are getting connected with this plugin. But somehow, it is not working for Motorola E2. I have try a lot but every time when i connect device with USB cable and then click on Connect button to get it connected by the WIFI, and then When i remove the cable, it get disconnected from the ADB.

Can you please check for this issue and let me know if anything to update from my side.

Sincerely,
Shreyash

**Comment by pedrovgs** [comment]
Sorry for the delay, I've been out for some time. @ShreyashPromact  there are some devices which do not support the debug over wifi feature. This plugin is just a UI executing the commands some adb commands. If the device does not support this feature I can not change the plugin code to get it working :S. Sorry, I'm closing this issue.

**Comment by ShreyashPromact** [comment]
@pedrovgs 

Thanks for reply.
If possible, can you please keep one note with the listing of all unsupported device that you came to know. It will help other developers  to know whether to use this library or not.

Sincerely,
Shreyash
