### ISSUE TITLE
Moto G3 connects fine but removing cable disconnects the device

### ISSUE THREAD

**Issue by sudhirkhanger** [pedrovgs/AndroidWiFiADB#39]
When I connect my Moto G3 to the Android Studio and click on the plugin icon I see that phone gets connected properly but at the same time when I remove the usb cable it is gone. No device is connected as soon as I remove the cable.

I am able to connect fine by `adb tcpip 5555`, remove cable, and `adb connect ip-address`.

**Comment by john1jan** [comment]
Same thing happens for me as well. When i connect usb cable it shows

List of devices attached
ZY222VM86H      device
172.17.94.7:5555        device
<img width="484" alt="screen shot 2016-04-15 at 11 53 00 am" src="https://cloud.githubusercontent.com/assets/4264813/14552991/9ee8e610-0300-11e6-9f90-0d8248fae162.png">

But when i disconnect usb, the device is also disconnects from wifi.

My device and System are connected to same wifi

**Comment by AlokBansal8** [comment]
Using Android Studio 2.1 Beta 2 and its not connecting with my Moto G2.

![screen shot 2016-04-16 at 9 33 29 am](https://cloud.githubusercontent.com/assets/12045853/14578991/952e919e-03b7-11e6-996c-bbbed3744eff.png)

Many a times it shows following message despite my computer and device are connected with same WiFi network.
![screen shot 2016-04-16 at 9 44 21 am](https://cloud.githubusercontent.com/assets/12045853/14579003/021eb964-03b8-11e6-9461-e54d6a89c33a.png)

Following also happens.
![screen shot 2016-04-17 at 8 55 28 am](https://cloud.githubusercontent.com/assets/12045853/14584871/b0139b30-047a-11e6-940e-c20c1e022af0.png)

**Comment by giaotuancse** [comment]
The same issue on Moto X 2014. And Anroid Studio 2.0

**Comment by giaotuancse** [comment]
UPDATED: Try to use terminal to connect when unplug the USB cable
Use command: "adb connect yourIP:yourPort" 
Ex: "adb connect 192.168.1.19:5555"

**Comment by sudhirkhanger** [comment]
@giaotuancse That's no news. If we had to do that we wouldn't need this plugin.

**Comment by pedrovgs** [comment]
Sorry for the delay, I've been out for some time. @sudhirkhanger @giaotuancse   there are some devices which do not support the debug over wifi feature. This plugin is just a UI executing the commands @giaotuancse pointed. If the device does not support this feature I can not change the plugin code to get it working :S. Sorry, I'm closing this issue.

**Comment by sudhirkhanger** [comment]
@pedrovgs If we are talking about the same thing what makes you think that Moto G3 doesn't support adb over wifi. I use my Moto G3 with adb over wifi every day for hours. It's the plugin which doesn't work.

**Comment by pedrovgs** [comment]
@sudhirkhanger what commands do you execute to connect your device over wifi? I'd like to know if the commands executed are different :)

**Comment by sudhirkhanger** [comment]
@pedrovgs 

```
Connect phone via usb
adb tcpip 5555
remove phone from usb
adb connect ip-address 
```

Exactly how it's discribed in the `adb` docs.
https://developer.android.com/tools/help/adb.html#wireless

**Comment by pedrovgs** [comment]
That's the command the plugin executes :( Could you debug the plugin and try to find the bug? All the devices I have are working as expected with the plugin and I don't have a Moto G3 :( Including my Nexus 5X and Nexus 6P.

**Comment by AlokBansal8** [comment]
@pedrovgs I am also running my Moto G2 phone using the commands mentioned in the developer site documentations.
Tell me, how can I debug the plugin?

**Comment by pedrovgs** [comment]
Thanks @AlokBansal8 you can clone the repository, run it and debug it from your IntelliJ :)
