### ISSUE TITLE
No icon 

### ISSUE THREAD

**Issue by rhespanhol** [pedrovgs/AndroidWiFiADB#4]
I installed this plugin today but the icon wasn't added to the toolbar

edit: added screenshot

![screen shot 2015-10-19 at 12 24 22](https://cloud.githubusercontent.com/assets/11316354/10576647/ca8ad872-765c-11e5-9c7c-84b724af8654.png)

**Comment by pedrovgs** [comment]
Hi @rhespanhol can you provide us some information related to the Android Studio or IntelliJ version you  are using, the operative system and a screenshot? Remember that in IntelliJ you have to enable your toolbar at: `View->Toolbar`Do you have this option enabled?

**Comment by rhespanhol** [comment]
Im using:
osx version 10.11
android studio 1.4

I know the plugin was installed because it shows at Tools > Android > ADB WIFI

**Comment by rhespanhol** [comment]
Sorry, i guess i must have downloaded the incorrect plugin from the repository. there is one with almost the same name
