### ISSUE TITLE
it can not work 

### ISSUE THREAD

**Issue by liuxgchi** [pedrovgs/AndroidWiFiADB#40]
I has download all the plugin you released,and it looks like work well,and can connect successfully. and i can find my device in the select dialog.I used the intellij, please help me! thanks

**Comment by pedrovgs** [comment]
I'm sorry @liuxgchi but I don't understand you at all :(

**Comment by liuxgchi** [comment]
I have found the reason, It can work but slowly, I have to wait for a moment ,and the app can run on the devices.
