### ISSUE TITLE
how can I promote the speed!

### ISSUE THREAD

**Issue by liuxgchi** [pedrovgs/AndroidWiFiADB#41]
My device can connect to the intellij, but after click the run button when the net is well, and I have to wait a long time util the device run the app.Please help me and tell me how can I promote the speed!

**Comment by lightcommy** [comment]
same problems

**Comment by pedrovgs** [comment]
Hi @liuxgchi and @lightcommy! To promote the speed configuration we depend on the Android adb implementation. This plugin just connects the device with your IDE using adb. If the adb implementation is slow I can't change the code to speed up the deploy process.
