### ISSUE TITLE
Manual adding feature

### ISSUE THREAD

**Issue by rdonuk** [pedrovgs/AndroidWiFiADB#42]
Hi, I am not able to connect devices via usb to my computer. So, I need to add devices with an add button manually. After I type the device IP and add to the window, with connect button it should be connect over wifi without usb connection. Is this possible?

Thank you.

**Comment by pedrovgs** [comment]
Hi @rdonuk!

This plugin is based on a adb feature which requires to connect the device using the usb cable. Using this plugin and adb it's impossible to connect your device through wifi without connecting it using your usb cable.
