### ISSUE TITLE
Cann't connect to my device

### ISSUE THREAD

**Issue by DysaniazzZ** [pedrovgs/AndroidWiFiADB#45]
When I'm trying to connect to my device, I get this "10060" error. I wanna know how to fix it anxiously.

`D:\Space\ASSpace\android>adb tcpip 5555
restarting in TCP mode port: 5555

D:\Space\ASSpace\android>adb connect 10.2.5.29
unable to connect to 10.2.5.29:5555: cannot connect to 10.2.5.29:5555: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 
(10060)
`

**Comment by pedrovgs** [comment]
Hi @DysaniazzZ I need more info.

What's your device model and OS version?
Did you get that trace executing that commands?
Is that the IP of your device?
Is the device connected to the usb cable while you execute the commands?

**Comment by DysaniazzZ** [comment]
Oh, My device is Meizu MX2 that is assembled in China. Its OS is Flyme OS 3.8.5A, which is based on Android 4.4.4. My Android Studio version is 2.1.2 and the Android WiFi ADB plugin version is the latest, v2.2. The "10.2.5.29" is the IP of my device and I can ping it. I keep my device connected to the usb cable while I execute the commands.

**Comment by pedrovgs** [comment]
The problem is that your device does not support adb over wifi connection. That's why if you execute:

```
D:\Space\ASSpace\android>adb tcpip 5555
restarting in TCP mode port: 5555

D:\Space\ASSpace\android>adb connect 10.2.5.29
unable to connect to 10.2.5.29:5555: cannot connect to 10.2.5.29:5555: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 
```

The result is "cannot connect to.....". I'm sorry but if your device does not support adb over wifi I can not change the plugin code to get it working :(
