### ISSUE TITLE
Devices dashboard

### ISSUE THREAD

**Issue by 471448446** [pedrovgs/AndroidWiFiADB#48]
Where can i find the Devices dashboard? thk
![image](https://cloud.githubusercontent.com/assets/7636279/18262614/deca0fb0-7435-11e6-938e-f2553f8c617d.png)

**Comment by pedrovgs** [comment]
Hi @471448446 you have to install the plugin, restart your IDE and open the lateral toolbar. There you'll find the Android WiFi ADB tab.

If you don't see that toolbar, please press the button you'll find at the right bottom corner of your screen. This button shows and hides the toolbar.

<img width="366" alt="screen shot 2016-09-06 at 10 27 11" src="https://cloud.githubusercontent.com/assets/4030704/18266762/818c7b1c-741c-11e6-83e0-fee8d8933d01.png">
