### ISSUE TITLE
Unable to connect device 'MI_4W'. Review your WiFi connection.

### ISSUE THREAD

**Issue by maoruibin** [pedrovgs/AndroidWiFiADB#5]
I connect Mobile Device to PC use Usb and  click that button, but AndroidStudio point 

```
 Android WiFi ADB
 Unable to connect device 'MI_4W'. Review your WiFi connection.
```

I am sure the wifi is same in mobile and pc

**Comment by pedrovgs** [comment]
@maoruibin can you paste here your device specifications: full device name, os version, etc? ADB does not support this feature with some devices.

**Comment by maoruibin** [comment]
full name:Xiaomi MI 4W
os version:4.4.4 KTU84P

I have a  another device Nexus6 and connect successfully ,I wish to you will fix XiaoMi bug , in china this company have a lot of users  include me, thanks advance.

**Comment by pedrovgs** [comment]
@maoruibin can you try just with your MI 4W connected with your USB? I'm not sure if the current version supports two devices connected at the same time.

**Comment by dhavaln** [comment]
Same error for me:
Device: Android One (Micromax AQ4501)
OS: 4.4.4

Though it works on my Nexus 7 with Android 4.4.4 so it must be some sort of device issue. I will look into the source over the weekend if I see can catch anything.

**Comment by pedrovgs** [comment]
@dhavaln do you have your Nexus 7 and your Micromax AQ4501 devices connected at the same time to your computer?

**Comment by dhavaln** [comment]
@pedrovgs No I am connecting only one at a time.

**Comment by pedrovgs** [comment]
@dhavaln  can you connect your device from command line? You have to execute:

```
adb tcpip 555
adb connect PUT_YOUR_DEVICE_IP_HERE
```

Can you paste here the result of the execution?

**Comment by maoruibin** [comment]
@pedrovgs Yes , Now  it is right ,connect successfully ,Thanks for your job ~

**Comment by dhavaln** [comment]
@pedrovgs It's working now. Thanks for the help. I didn't fire both the commands, I restarted adb on 555 and then clicked the Adb Wifi icon in Android Studio and got connected message. I tested with both the devices connected and it working as well. Thanks for the help.

**Comment by pedrovgs** [comment]
Cool thanks!
