### ISSUE TITLE
About Intellij Plugin

### ISSUE THREAD

**Issue by ghost** [pedrovgs/AndroidWiFiADB#51]
Hi,I try to write a plugin to use `adb push` ,But I can not get the `adb` command.
I read your code , find you use the `AndroidSdkUtils.getAndroidSdkPathsFromExistingPlatforms()`,but I can not import `AndroidSdkUtils`
Could you tell me why? Please.
(sorry for my English)

**Comment by pedrovgs** [comment]
Hi @HongnianZhang without reading your code I don't know what could be wrong. Review the dependencies added to your plugin configuration. If I'm not wrong there is one related to the Android SDK you need.
