### ISSUE TITLE
(Mac) install apk slowly in the install step

### ISSUE THREAD

**Issue by njleonzhang** [pedrovgs/AndroidWiFiADB#59]
with this plugin, it's convenient, but in `instal apk` step , it is very slow.

**Comment by pedrovgs** [comment]
I'm really sorry but this does not depend on the plugin code. The APK installation is based on ``adb`` and your wifi connection. This is somethign we can't fix changing the plugin.

**Comment by njleonzhang** [comment]
OK, tnx
