### ISSUE TITLE
How to use my mobile self network data?

### ISSUE THREAD

**Issue by kaixuanluo** [pedrovgs/AndroidWiFiADB#62]
4G? I need this.

**Comment by pedrovgs** [comment]
Honestly, I have no idea. I never tried to use this plugin using tethering!

**Comment by kaixuanluo** [comment]
Well, My English is not well, My mean is when my phone was connected AndroidWiFiADB ,  I can't use the 4G. If my app can only use the 4G, That mean i can't use the AndroidWiFiADB?
