### ISSUE TITLE
Slow speed when installing large apk.

### ISSUE THREAD

**Issue by SnakeEys** [pedrovgs/AndroidWiFiADB#7]
My project is pretty large so it takes me too much time to build or install, besides, sometimes it can't be installed to my phone with the ERROR INSTALL_FAILED_INVALID_APK;
Is there any ways of improving the speed of installing large apk to my phone?
p.s Computer Info: 8GB RAM, 5400HDD, x86 64 Windows 7,
      phone: nexus 5 android 5.1.1; HUAWEI MATE 7;

**Comment by pedrovgs** [comment]
I'm sorry @Cold-Snake but this plugin is using the Android Debug Bridge to start the WiFi connection and all the problems related to the performance or the apk installation can't be fixed changing the code of this project.

**Comment by SnakeEys** [comment]
@pedrovgs 
Thanks a lot, I'll do it as you say.
