### ISSUE TITLE
can not uninstall in AndroidStudio 1.4.0

### ISSUE THREAD

**Issue by takboo** [pedrovgs/AndroidWiFiADB#8]
i can't uninstall AndroidWiFiADB in AndroidStudio 1.4.0 and i can't use it,because there is no button on the bar.

**Comment by pedrovgs** [comment]
@takboo can't you install it or uninstall it?

**Comment by pinakinkansara** [comment]
@pedrovgs ,On Android Studio version 1.4 cant get plugin in the  Settings -> Plugin -> Browse Repositories , When search Android WiFi ADB

**Comment by 3dm1** [comment]
Search for ADB Wifi, and you should find it and be able to install.

**Comment by pinakinkansara** [comment]
That is different plugin .not yours

On Wed 21 Oct, 2015 11:08 pm Edson Menegatti notifications@github.com
wrote:

> Search for ADB Wifi, and you should find it and be able to install.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pedrovgs/AndroidWiFiADB/issues/8#issuecomment-149972746
> .
> 
> ## 

_Pinakin Kansara_ / Sr Mobile Application Developer
pinakin.k.kansara@gmail.com / +91 9099721222/

 Skype :- pinakin.kansara

_Vedanta Soft_

www.vedantasoft.com http://signature-maker.net/www.vedantasoft.com
